apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-cluster-issuer
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: yamazawa@supersoftware.co.jp
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}