apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: domain-cert
  namespace: weave
spec:
  secretName: domain-tls
  issuerRef:
    name: letsencrypt-prod-cluster-issuer
    kind: ClusterIssuer
  commonName: weave.kubernetes.cf
  acme:
    config:
    - http01: {}
      domains:
      - weave.kubernetes.cf