apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: weave
  namespace: weave
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/target: 51.15.39.110
    external-dns.alpha.kubernetes.io/target: 51.15.85.186
spec:
  tls:
  - hosts:
    - weave.kubernetes.cf
    secretName: domain-tls
  rules:
  - host: weave.kubernetes.cf
    http:
      paths:
      - backend:
          serviceName: weave-scope-app
          servicePort: 80
        
